version: '3.8'

networks:
  perf_network:
    driver: bridge

services:
  mongo-j4:
    image: mongo:7.0
    container_name: mongo-j4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ipssi2025
    ports:
      - "27017:27017"
    networks:
      - perf_network
